[package]
name = "FabChess"
version = "0.1.0"
authors = ["fabianvdW"]
edition = "2018"

[dependencies]
lazy_static = "1.2.0"
rand = "0.6.4"
[profile.release]
opt-level=3
debug=false
codegen-units=5
lto=true
[profile.test]
opt-level=3
debug=true
[lib]
name="core"
path= "src/lib.rs"
[[bin]]
name="schach_reworked"
path="src/main.rs"
[[bin]]
name="spielleiter"
path="src/spielleiter.rs"
