[package]
name = "SchachReworked"
version = "0.1.0"
authors = ["fabianvdW"]
edition = "2018"

[dependencies]
lazy_static = "1.2.0"
rand = "0.6.4"
[profile.release]
opt-level=3
debug=false
[profile.test]
opt-level=3
debug=true